"""UUIDv7 (RFC 9562) generator. Python 3.12's ``uuid`` module has no ``uuid7``.

Layout (128 bits)::

    unix_ts_ms (48) | ver=0b0111 (4) | rand_a (12) | var=0b10 (2) | rand_b (62)

``rand_a`` holds a 12-bit counter (RFC 9562 §6.2, method 1) seeded randomly each
millisecond, so IDs generated by one process are strictly increasing even within
the same millisecond or if the clock steps backwards.
"""

import secrets
import threading
import time
import uuid

_MAX_TS = (1 << 48) - 1
_MAX_COUNTER = 0xFFF

_lock = threading.Lock()
_last_ms = 0
_counter = 0


def _next_timestamp_and_counter() -> tuple[int, int]:
    global _last_ms, _counter
    with _lock:
        now_ms = time.time_ns() // 1_000_000
        if now_ms > _last_ms:
            _last_ms = now_ms
            # Leave headroom so the counter rarely overflows within one millisecond.
            _counter = secrets.randbits(11)
        else:
            _counter += 1
            if _counter > _MAX_COUNTER:
                # Counter exhausted: borrow the next millisecond to stay monotonic.
                _last_ms += 1
                _counter = secrets.randbits(11)
        return _last_ms, _counter


def uuid7() -> uuid.UUID:
    ts_ms, counter = _next_timestamp_and_counter()
    value = (
        ((ts_ms & _MAX_TS) << 80)
        | (0x7 << 76)
        | (counter << 64)
        | (0b10 << 62)
        | secrets.randbits(62)
    )
    return uuid.UUID(int=value)


def uuid7_timestamp_ms(value: uuid.UUID) -> int:
    """The Unix timestamp in milliseconds embedded in a UUIDv7."""
    return value.int >> 80
